module.exports = {
  PUBLIC: "PUBLIC",
  USER: "USER",
  GLOBAL_ADMIN: "GLOBAL_ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
  SITE_ADMIN: "SITE_ADMIN",
  STATE_ADMIN: "STATE_ADMIN",
  COUNTRY_ADMIN: "COUNTRY_ADMIN",
};
