module.exports = {
	CREATE: "CREATE",
	FETCH: "FETCH",
	SEARCH: "SEARCH",
	UPDATE: "UPDATE",
	REMOVE: "REMOVE",
	ADD_CATEGORY: "ADD_CATEGORY",
	REMOVE_CATEGORY: "REMOVE_CATEGORY",
	ADD_QUANTITY: "ADD_QUANTITY",
	UPDATE_QUANTITY: "UPDATE_QUANTITY",
	REMOVE_QUANTITY: "REMOVE_QUANTITY",
	GENERATE_TOKEN: "GENERATE_TOKEN"
};