module.exports = {
  CREATE: "CREATE",
  GENERATE_TOKEN: "GENERATE_TOKEN",
  DELETE: "DELETE",
  ADD_DATA: "ADD_DATA",
  REGISTER: "REGISTER",
  UPDATE: "UPDATE",
  RESET_PASSWORD: "RESET_PASSWORD",
};
