-- MySQL Script generated by MySQL Workbench
-- Mon Sep 28 02:08:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema madhuram
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `madhuram` ;

-- -----------------------------------------------------
-- Schema madhuram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `madhuram` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `madhuram` ;

-- -----------------------------------------------------
-- Table `madhuram`.`user_credentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`user_credentials` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`user_credentials` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(256) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `role` VARCHAR(100) NOT NULL DEFAULT 'customer',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`customers` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`customers` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `customer_id` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `email` VARCHAR(100) NULL,
  `phone_number` BIGINT(13) NOT NULL,
  `country_code` SMALLINT NOT NULL DEFAULT 91,
  `timezone` VARCHAR(100) NOT NULL DEFAULT 'Asia/Kolkata',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `user_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcustomers_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE,
  UNIQUE INDEX `is_deleted_UNIQUE` (`is_deleted` ASC) VISIBLE,
  INDEX `fk_customers_user_credentials1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_user_credentials1`
    FOREIGN KEY (`user_id`)
    REFERENCES `madhuram`.`user_credentials` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`customer_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`customer_cards` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`customer_cards` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `card_number` BIGINT(16) NOT NULL,
  `expiry_year` SMALLINT NOT NULL,
  `expiry_month` SMALLINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `customer_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_customer_cards_customers1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_cards_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `madhuram`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`billing_addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`billing_addresses` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`billing_addresses` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `address_1` VARCHAR(4000) NOT NULL,
  `address_2` VARCHAR(4000) NULL,
  `address_3` VARCHAR(4000) NULL,
  `phone_number` BIGINT(13) NULL,
  `pincode` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`transactions` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`transactions` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `card_number` BIGINT(16) NOT NULL,
  `expiry_year` INT NOT NULL,
  `expiry_month` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `customer_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_customers1_idx` (`customer_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `madhuram`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`payments` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`payments` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `payment_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `transaction_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_payments_transactions1_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_transactions1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `madhuram`.`transactions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`orders` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`orders` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `order_id` VARCHAR(256) NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `customer_id` VARCHAR(256) NOT NULL,
  `billing_address_id` BIGINT(20) NOT NULL,
  `payment_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `created_at`, `updated_at`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `fk_orders_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_orders_billing_addresses1_idx` (`billing_address_id` ASC) VISIBLE,
  INDEX `fk_orders_payments1_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `madhuram`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_billing_addresses1`
    FOREIGN KEY (`billing_address_id`)
    REFERENCES `madhuram`.`billing_addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_payments1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `madhuram`.`payments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`invoices` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`invoices` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `content` BLOB NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `order_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`, `order_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_invoices_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `madhuram`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`contacts` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`contacts` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `address_1` VARCHAR(4000) NOT NULL,
  `address_2` VARCHAR(4000) NULL,
  `address_3` VARCHAR(4000) NULL,
  `phone_number` BIGINT(13) NULL,
  `pincode` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `customer_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_contacts_customers1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_contacts_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `madhuram`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`staff_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`staff_details` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`staff_details` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `email` VARCHAR(256) NULL,
  `phone_number` BIGINT(13) NULL,
  `country_code` SMALLINT NULL,
  `timezone` VARCHAR(100) NOT NULL DEFAULT 'Asia/Kolkata',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `user_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_staff_details_user_credentials1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_details_user_credentials1`
    FOREIGN KEY (`user_id`)
    REFERENCES `madhuram`.`user_credentials` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`products` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`products` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `product_id` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `description` VARCHAR(4000) NULL,
  `thumbnail_url` VARCHAR(4000) NULL DEFAULT 'null',
  `rating` DECIMAL(3,2) NOT NULL DEFAULT 0,
  `display_priority` BIGINT(10) NULL,
  `sales_count` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`product_favourites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`product_favourites` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`product_favourites` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `status` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `customer_id` VARCHAR(256) NOT NULL,
  `product_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_product_favourites_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_product_favourites_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_favourites_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `madhuram`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_favourites_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `madhuram`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`categories` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`categories` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`product_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`product_categories` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`product_categories` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `product_id` VARCHAR(256) NOT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_product_categories_products1_idx` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_product_categories_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_categories_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `madhuram`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `madhuram`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`product_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`product_details` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`product_details` (
  `id` BIGINT(20) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1000,
  `listing_price` DECIMAL(8,2) NOT NULL,
  `sale_price` DECIMAL(8,2) NOT NULL,
  `discount` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `product_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_product_details_products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_details_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `madhuram`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`order_items` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`order_items` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `count` INT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `order_id` VARCHAR(256) NOT NULL,
  `product_detail_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_items_orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_items_product_details1_idx` (`product_detail_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `madhuram`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_product_details1`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `madhuram`.`product_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`shipping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`shipping` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`shipping` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `shipping_id` VARCHAR(256) NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `estimated_delivery_date` TIMESTAMP NULL,
  `actual_delivery_date` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `contact_id` BIGINT(20) NOT NULL,
  `orders_id` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `shipping_id_UNIQUE` (`shipping_id` ASC) VISIBLE,
  INDEX `fk_shipping_orders1_idx` (`orders_id` ASC) VISIBLE,
  INDEX `fk_shipping_contacts1_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `fk_shipping_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `madhuram`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipping_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `madhuram`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`shopping_cart` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`shopping_cart` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `customer_id` VARCHAR(256) NOT NULL,
  `contact_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `customer_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_shopping_cart_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_shopping_cart_contacts1_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `madhuram`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_cart_contacts1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `madhuram`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`shopping_cart_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`shopping_cart_items` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`shopping_cart_items` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `count` INT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `shopping_cart_id` BIGINT(20) NOT NULL,
  `product_detail_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_shopping_cart_items_shopping_cart1_idx` (`shopping_cart_id` ASC) VISIBLE,
  INDEX `fk_shopping_cart_items_product_details1_idx` (`product_detail_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_items_shopping_cart1`
    FOREIGN KEY (`shopping_cart_id`)
    REFERENCES `madhuram`.`shopping_cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_cart_items_product_details1`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `madhuram`.`product_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `madhuram`.`app_clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `madhuram`.`app_clients` ;

CREATE TABLE IF NOT EXISTS `madhuram`.`app_clients` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `client_id` VARCHAR(256) NOT NULL,
  `client_secret` VARCHAR(1000) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
